# Thalloo Starter Template
#
# This project uses Jekyll to integrate with GitHub Pages.
# Configure the basic settings below to configure your copy.

# Your site settings
title: ESMAP Clean Cooking Evidence Map 
description: > # this means to ignore newlines until "baseurl:"
  A map of the evidence base of drivers and barriers towards clean cooking
baseurl: "/evidencemap" # the subpath of your site, e.g. /blog
url: "https://esmap.github.io" # the base hostname & protocol for your site
ownername: "Energy Sector Management Assistance Program"
ownerurl: "https://www.esmap.org/"

# Internal configuration
plugins:
  - jekyll-remote-theme
remote_theme: AndrewIOM/thalloo
markdown: kramdown
collections:
  maps:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"